Задание5**

In [3]:
# 1
import numpy as np
a = np.array([i for i in range(12, 24)])
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [20]:
# 2
o = a.reshape(3, 4)
t = a.reshape(4, 3)
tr = a.reshape(2, 6)
f = a.reshape(6, 2)
v = a.reshape(12, 1)
o, t, tr, f, v

(array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]))

In [24]:
# 3
one = a.reshape(3, -1)
two = a.reshape(4, -1)
three = a.reshape(2, -1)
four = a.reshape(-1, 2)
five = a.reshape(-1, 1)
one, two, three, four, five

(array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]))

Массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным не можем.

In [69]:
# 5
b = np.random.randn(3, 4)
bd = b.flatten()
bd
# почему-то у меня не работает все, что связано с size/resize (не находит такие функции)

array([[ 0.71182925, -0.47019107,  0.33321282, -1.12452787],
       [-0.36599697,  3.09268931, -0.20187599, -0.44281577],
       [ 0.19907467,  1.37860249, -0.03967818,  0.25444553]])

In [50]:
# 6
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [55]:
# 7
b = np.arange(20, 1, -2).reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

Разница между массивом а и b в том, что массив а одномерный, b - двумерный.

In [73]:
# 8
a = np.zeros((2, 2))
b = np.ones((3, 2))
v = np.concatenate((a, b), axis = 0)
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [84]:
# 9
a = np.arange(0, 12)
A = a.reshape(4, 3)
At = A.T
B = np.dot(A, At)
B.shape

# Найти обратную матрицу матрице В невозможно, поскольку это сингулярная необратимая матрица, не имеющая единственного
# уникального решения.

(4, 4)

In [87]:
# 10
np.random.seed(42)

In [88]:
# 11
a = np.arange(0, 16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [94]:
# 12
C = a.reshape(4, 4)
D = np.add(B, C * 10)
np.linalg.det(D)
np.linalg.matrix_rank(D)
D_inv = np.linalg.inv(D)
D_inv

array([[ 1.10382344e+13,  5.26315789e-02, -3.31147031e+13,
         2.20764688e+13],
       [-8.46264636e+13,  9.38249922e+13,  6.62294063e+13,
        -7.54279349e+13],
       [ 1.36138224e+14, -1.87649984e+14, -3.31147031e+13,
         8.46264636e+13],
       [-6.25499948e+13,  9.38249922e+13,  0.00000000e+00,
        -3.12749974e+13]])

In [95]:
# 13
mask_neg = D_inv < 0
mask_pos = D_inv > 0
D_inv[mask_neg] = 0
D_inv[mask_pos] = 1
D_inv

array([[1., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 0.]])

In [96]:
E = np.where(D_inv, B, C)
E

array([[  5,  14,   2,  32],
       [  4,  50,  86,   7],
       [ 23,   9,  10, 212],
       [ 12, 122,  14,  15]])